USE [BD_II]
GO

/****** Object:  StoredProcedure [dbo].[paEliminarJornada]    Script Date: 13/03/2021 21:04:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[paEliminarJornada]
@jor_codigo CHAR(10)
AS
IF EXISTS (SELECT 1 FROM JORNADA WHERE jor_codigo=@jor_codigo)
BEGIN 
	IF NOT EXISTS (SELECT 1 FROM GRUPO WHERE jor_codigo=@jor_codigo)
		BEGIN
			DELETE FROM  JORNADA WHERE jor_codigo=@jor_codigo
			SELECT 'JORNADA SE ELIMINO CORRECTAMENTE' AS RESULTADO
		END
	ELSE
		BEGIN
			SELECT 'NO SE PUEDE ELIMINAR JORNADA, TIENE RELACIONES EN GRUPO.' AS RESULTADO
		END
END
ELSE
	BEGIN
		SELECT 'JORNADA NO EXISTE' AS RESULTADO
	END
GO

