USE [BD_II]
GO

/****** Object:  StoredProcedure [dbo].[paEliminarSemestre]    Script Date: 13/03/2021 21:04:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[paEliminarSemestre]
@sem_codigo CHAR(10)
AS
IF EXISTS (SELECT 1 FROM SEMESTRE WHERE sem_codigo=@sem_codigo)
BEGIN 
	IF NOT EXISTS (SELECT 1 FROM GRUPO WHERE sem_codigo=@sem_codigo)
		BEGIN
			DELETE FROM  SEMESTRE WHERE sem_codigo=@sem_codigo
			SELECT 'SEMESRE SE ELIMINO CORRECTAMENTE' AS RESULTADO
		END
	ELSE
		BEGIN
			SELECT 'NO SE PUEDE ELIMINAR SEMESTRE, TIENE RELACIONES EN GRUPO.' AS RESULTADO
		END
END
ELSE
	BEGIN
		SELECT 'SEMESTRE NO EXISTE' AS RESULTADO
	END
GO

