USE [BD_II]
GO

/****** Object:  StoredProcedure [dbo].[paEliminarCarrera]    Script Date: 13/03/2021 21:01:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[paEliminarCarrera]
@car_codigo CHAR(10)
AS
IF EXISTS (SELECT 1 FROM CARRERA WHERE car_codigo=@car_codigo)
BEGIN 
	IF NOT EXISTS (SELECT 1 FROM GRUPO WHERE car_codigo=@car_codigo)
		BEGIN
			DELETE FROM  CARRERA WHERE car_codigo=@car_codigo
			SELECT 'CARRERA SE ELIMINO CORRECTAMENTE' AS RESULTADO
		END
	ELSE
		BEGIN
			SELECT 'NO SE PUEDE ELIMINAR CARRERA, TIENE RELACIONES EN GRUPO.' AS RESULTADO
		END
END
ELSE
	BEGIN
		SELECT 'CARRERA NO EXISTE' AS RESULTADO
	END
GO

