USE FACTURACION_
--A
select pai_codigo as [Nombre País] from PAIS where pai_codigo  between 08 and 17 order by pai_codigo DESC;
--B
select TOP 5 ven_nombre, ven_apellido, fac_total from FACTURAENCABEZADO INNER JOIN VENDEDOR on FACTURAENCABEZADO.VEN_CODIGO = VENDEDOR.VEN_CODIGO order by FAC_TOTAL DESC;
--C
select CLI_EMAIL, FAC_DESCUENTO   from CLIENTE INNER JOIN FACTURAENCABEZADO on FACTURAENCABEZADO.CLI_CODIGO=CLIENTE.CLI_CODIGO where FAC_DESCUENTO  < 16000 order by FAC_DESCUENTO DESC;
--D
select MAR_DESCRIPCION, PRO_CODIGO from MARCA INNER JOIN PRODUCTO on PRODUCTO.MAR_CODIGO = MARCA.MAR_CODIGO  WHERE PRO_CODIGO=4000
SELECT * FROM MARCA