--LDD--
--CREAR BASE DE DATOS--
CREATE DATABASE PUBLICIDAD
USE PUBLICIDAD

--CREAR TABLA CLIENTE--
CREATE TABLE CLIENTE(
	cliCodigo CHAR (4) NOT NULL,
	cliNomnbre VARCHAR (20) NOT NULL,
   	cliApellido VARCHAR (20)  NOT NULL,
   	cliDireccion VARCHAR (30)  NOT NULL,
   	CONSTRAINT PK_CLIENTE PRIMARY KEY (cliCodigo),--PK--
)

--CREAR TABLA ANUNCIO--
CREATE TABLE ANUNCIO(
	anunCodigo CHAR (4) NOT NULL,
	anunTitulo VARCHAR (50) NOT NULL,
   	anunPrecio MONEY  NOT NULL,
   	CONSTRAINT PK_ANUNCIO PRIMARY KEY (anunCodigo),--PK--
)
--AÑADIR CAMPO cliCodigo y tipCodigo--
ALTER TABLE ANUNCIO ADD cliCodigo CHAR (4) NOT NULL
ALTER TABLE ANUNCIO ADD tipCodigo CHAR (4) NOT NULL

--CREAR FK ENTRE ANUNCIO Y CLIENTE--
ALTER TABLE ANUNCIO ADD CONSTRAINT FK_ANUNCIO_CLIENTE FOREIGN KEY (cliCodigo) REFERENCES CLIENTE (cliCodigo);
--CREAR FK ENTRE ANUNCIO Y TIPO--
ALTER TABLE ANUNCIO ADD CONSTRAINT FK_ANUNCIO_TIPO FOREIGN KEY (tipCodigo) REFERENCES TIPO (tipCodigo);

--CREAR TABLA TIPO--
CREATE TABLE TIPO(
	tipCodigo CHAR (4) NOT NULL,
	tipTipoAnuncio VARCHAR (50) NOT NULL,
   	CONSTRAINT PK_TIPO PRIMARY KEY (tipCodigo),--PK--
)

--CREAR TABLA DURACION--
CREATE TABLE DURACION(
	durCodigo CHAR (4) NOT NULL,
	durFechaInicio DATE NOT NULL,
	durFechaFin DATE NOT NULL,
   	CONSTRAINT PK_DURACION PRIMARY KEY (durCodigo),--PK--
)

--CREAR TABLA TRANSMISION--
CREATE TABLE TRANSMISION(
	transCodigo CHAR (4) NOT NULL,
	transUrlAnuncio VARCHAR (30) NOT NULL,
   	CONSTRAINT PK_TRANSMISION PRIMARY KEY (transCodigo),--PK--
)
--AÑADIR CAMPO anunCodigo y durCodigo--
ALTER TABLE TRANSMISION ADD anunCodigo CHAR (4) NOT NULL;
ALTER TABLE TRANSMISION ADD durCodigo CHAR (4) NOT NULL;

--CREAR FK ENTRE TRANSMISION Y ANUNCIO--
ALTER TABLE TRANSMISION ADD CONSTRAINT FK_TRANSMISION_ANUNCIO FOREIGN KEY (anunCodigo) REFERENCES ANUNCIO (anunCodigo);
--CREAR FK ENTRE TRANSMISION Y DURACION--
ALTER TABLE TRANSMISION ADD CONSTRAINT FK_TRANSMISION_DURACION FOREIGN KEY (durCodigo) REFERENCES DURACION (durCodigo);

--REGISTROS TIPO--
INSERT INTO TIPO (tipCodigo,tipTipoAnuncio)
SELECT '1','Banner' UNION ALL
SELECT '2','Popup'UNION ALL
SELECT '3','Patrocinado'

--REGISTROS CLIENTE--
INSERT INTO CLIENTE(cliCodigo,cliNomnbre,cliApellido,cliDireccion)
SELECT '1000','Paola','Gomez', 'Calle 21A 24-10' UNION ALL
SELECT '1001','Carlos','Valencia', 'Av 46 #45-90' UNION ALL
SELECT '1002','Diana','Diaz', 'Calle 11 #5-28' UNION ALL
SELECT '1003','Carolina','Montes', 'Calle 89 #56-98' UNION ALL
SELECT '1004','Luis','Perez', 'Cr 4 #4-78' 

--REGISTROS ANUNUNCIO--
INSERT INTO ANUNCIO(anunCodigo,anunTitulo,anunPrecio,cliCodigo,tipCodigo)
SELECT '2000','No más en Cali',100000, '1000','1' UNION ALL
SELECT '2001','Colombia',500000, '1001','3' UNION ALL
SELECT '2002','Las Fotomultas',350000, '1002','3' UNION ALL
SELECT '2003','Juegos',50000, '1003','2' UNION ALL
SELECT '2004','Las TICS',280000, '1004','1'

--REGISTROS DURACION--
 INSERT INTO DURACION(durCodigo,durFechaInicio,durFechaFin)
SELECT '3000','11/01/2019','12/02/2019' UNION ALL
SELECT '3001','10/01/2019','11/02/2019' UNION ALL
SELECT '3002','09/01/2019','10/02/2019' UNION ALL
SELECT '3003','08/01/2019','09/02/2019' UNION ALL
SELECT '3004','07/01/2019','08/03/2019' UNION ALL
SELECT '3005','06/02/2019','07/03/2019' UNION ALL
SELECT '3006','05/03/2019','04/04/2019' UNION ALL
SELECT '3007','04/04/2019','05/06/2019' 

--REGISTROS TRANSMISION--
 INSERT INTO TRANSMISION(transCodigo,transUrlAnuncio,anunCodigo, durCodigo)
SELECT '4000','www.ock.com','2000','3001' UNION ALL
SELECT '4001','www.ipny.com','2000','3002' UNION ALL
SELECT '4002','www.ock.com','2001','3003' UNION ALL
SELECT '4003','www.cali.com','2002','3004' UNION ALL
SELECT '4004','www.utap.com','2002','3005' UNION ALL
SELECT '4005','www.bey.com','2003','3006' UNION ALL
SELECT '4006','www.grapp.com','2004','3007' UNION ALL
SELECT '4007','www.color.com','2004','3000' 




--SELECCIONAR CLIENTE QUE TIENE UN ANUNCIO TIPO Banner--
SELECT cliNomnbre, cliApellido, tipTipoAnuncio
FROM CLIENTE, TIPO, ANUNCIO
WHERE ANUNCIO.cliCodigo = CLIENTE.cliCodigo
AND ANUNCIO.tipCodigo = TIPO.tipCodigo
AND tipTipoAnuncio ='Banner'

--SELECIONAR CLIENTE QUE TIENE UNA TRANSMISION EN LA URL www.utap.com--
SELECT cliNomnbre, cliApellido, transUrlAnuncio
FROM CLIENTE, TRANSMISION, ANUNCIO
WHERE ANUNCIO.cliCodigo = CLIENTE.cliCodigo
AND ANUNCIO.anunCodigo = TRANSMISION.anunCodigo
AND transUrlAnuncio ='www.utap.com'