USE [BD_II]
GO

/****** Object:  Table [dbo].[DEPARTAMENTO]    Script Date: 17/03/2021 11:21:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPARTAMENTO](
	[dep_codigo] [char](10) NOT NULL,
	[dep_nombre] [char](40) NOT NULL,
	[pai_codigo] [char](10) NOT NULL,
 CONSTRAINT [PK_DEPARTAMENTO] PRIMARY KEY CLUSTERED 
(
	[dep_codigo] ASC,
	[pai_codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEPARTAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTAMENTO_PAIS] FOREIGN KEY([pai_codigo])
REFERENCES [dbo].[PAIS] ([pai_codigo])
GO

ALTER TABLE [dbo].[DEPARTAMENTO] CHECK CONSTRAINT [FK_DEPARTAMENTO_PAIS]
GO

