USE [BD_II]
GO

/****** Object:  Table [dbo].[GRUPO]    Script Date: 17/03/2021 11:22:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GRUPO](
	[grup_codigo] [char](20) NOT NULL,
	[jor_codigo] [char](10) NOT NULL,
	[sem_codigo] [char](10) NOT NULL,
	[car_codigo] [char](10) NOT NULL,
	[grup_descripcion] [varchar](60) NOT NULL,
 CONSTRAINT [PK_GRUPO] PRIMARY KEY CLUSTERED 
(
	[grup_codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GRUPO]  WITH CHECK ADD  CONSTRAINT [FK_GRUPO_CARRERA] FOREIGN KEY([car_codigo])
REFERENCES [dbo].[CARRERA] ([car_codigo])
GO

ALTER TABLE [dbo].[GRUPO] CHECK CONSTRAINT [FK_GRUPO_CARRERA]
GO

ALTER TABLE [dbo].[GRUPO]  WITH CHECK ADD  CONSTRAINT [FK_GRUPO_JORNADA] FOREIGN KEY([jor_codigo])
REFERENCES [dbo].[JORNADA] ([jor_codigo])
GO

ALTER TABLE [dbo].[GRUPO] CHECK CONSTRAINT [FK_GRUPO_JORNADA]
GO

ALTER TABLE [dbo].[GRUPO]  WITH CHECK ADD  CONSTRAINT [FK_GRUPO_SEMESTRE] FOREIGN KEY([sem_codigo])
REFERENCES [dbo].[SEMESTRE] ([sem_codigo])
GO

ALTER TABLE [dbo].[GRUPO] CHECK CONSTRAINT [FK_GRUPO_SEMESTRE]
GO

