USE [BD_II]
GO

/****** Object:  Table [dbo].[JORNADA]    Script Date: 17/03/2021 11:22:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JORNADA](
	[jor_codigo] [char](10) NOT NULL,
	[jor_nombre] [char](20) NOT NULL,
 CONSTRAINT [PK_JORNADA] PRIMARY KEY CLUSTERED 
(
	[jor_codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

