USE [BD_II]
GO

/****** Object:  Table [dbo].[SEMESTRE]    Script Date: 17/03/2021 11:24:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEMESTRE](
	[sem_codigo] [char](10) NOT NULL,
	[sem_nombre] [char](40) NOT NULL,
 CONSTRAINT [PK_SEMESTRE] PRIMARY KEY CLUSTERED 
(
	[sem_codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

