USE FACTURACION_
SELECT * FROM FACTURADETALLE
/*FUNCIONES DE AGREGADO*/
/*
COUNT = CUENTA
SUM = SUMA
MAX = MAXIMO
MIN = MINIMO
*/

--CONTAR CUANTAS FACTURAS TENGO--
SELECT COUNT(FAC_NUMERO) FROM FACTURADETALLE
--CONTAR CUANTAS FACTURAS(fac_total) HAY MAYORES A 70.000--
SELECT COUNT(FAC_NUMERO) FROM FACTURADETALLE WHERE FAC_TOTAL > 70000

--CUAL ES EL TOTAL DE LA SUMA DE FAC_TOTAL--
SELECT SUM(FAC_TOTAL) FROM FACTURADETALLE

SELECT * FROM PRODUCTO
--SABER CUAL ES EL PODUCTO QUE ME CUESTA MAS--
SELECT MAX(PRO_PRECIO) AS [PRECIO PRODUCTO] FROM PRODUCTO

--SABER CUAL ES EL PODUCTO QUE MENOS ME CUESTA--
SELECT MIN(PRO_PRECIO) AS [PRECIO PRODUCTO] FROM PRODUCTO